Repository nextcloud/nextcloud_announcements, pull requests merged in 2024-07, with the labels that each got.

#356 Add SPDX header
  .gitattributes
  .github/contributing.md
  .github/dependabot.yml
  .github/issue_template.md.license
  .github/workflows/block-merge-freeze.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  .gitignore
  .php-cs-fixer.dist.php
  .reuse/dep5
  AUTHORS.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  appinfo/info.xml
  img/app-dark.svg
  img/app.svg
  lib/AppInfo/Application.php
  lib/Cron/Crawler.php
  lib/Notification/Notifier.php
  psalm.xml
Labels: 3. to review, technical debt

#357 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#358 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#359 Migrate REUSE to TOML format
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#360 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#363 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#364 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#347 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#362 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#367 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#365 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#368 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#366 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
